# Generated by Django 4.2.23 on 2026-01-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_customuser_email_otp_customuser_is_email_verified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("otp", models.CharField(max_length=6)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
