# Generated by Django 4.2.23 on 2026-01-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_emailotp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailOTP",
        ),
    ]
